### ISSUE TITLE
setKey() on client is not optional

### ISSUE THREAD

**Issue by rafaeltovar** [ankitpokhrel/tus-php#203]
**Describe the bug**

Im implementing the Client library of v1.0.12 and if i don't use `setKey` (the documentation say that is optional) the system report me:

```
PHP Fatal error:  Uncaught TypeError: Return value of TusPhp\Tus\Client::getKey() must be of the type string, null returned in .../vendor/ankitpokhrel/tus-php/src/Tus/Client.php:272
Stack trace:
#0 /.../vendor/ankitpokhrel/tus-php/src/Tus/Client.php(282): TusPhp\Tus\Client->getKey()
#1 /.../vendor/ankitpokhrel/tus-php/src/Tus/Client.php(539): TusPhp\Tus\Client->getUrl()
#2 /.../vendor/ankitpokhrel/tus-php/src/Tus/Client.php(380): TusPhp\Tus\Client->sendHeadRequest()
#3 /.../test/upload.php(24): TusPhp\Tus\Client->upload(1000000)
```

**To Reproduce**

```php
$client = new \TusPhp\Tus\Client($baseUrl);

// Optional. If key is not set explicitly, the system will generate an unique uuid.
$key = 'your unique key';

//$client->setKey($key)->file('/path/to/file', 'filename.ext');
$client->file('/path/to/file', 'filename.ext');

// Create and upload a chunk of 1MB
$bytesUploaded = $client->upload(1000000);

// Resume, $bytesUploaded = 2MB
$bytesUploaded = $client->upload(1000000);
```

**Expected behavior**
The system will generate an unique uuid.

**Comment by ankitpokhrel** [comment]
Yes, the key is mandatory. Thank you for bringing this up.
