### ISSUE TITLE
cannot run example

### ISSUE THREAD

**Issue by muniv11111** [ankitpokhrel/tus-php#304]
Hello,
 in basic example I endup with POST 500 error with upload.php.

In apache error log I see:

[php7:error] [pid 49085] [client 127.0.0.1:42298] PHP Fatal error:  Uncaught GuzzleHttp\\Exception\\ClientException: Client error: `POST http://dog.seedhost.eu/muniv/downloads/tus-php/files` resulted in a `401 Unauthorized` response: Unauth (truncated...)\n in /home24/muniv/downloads/tus-php/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113\nStack trace:\n#0 /home24/muniv/downloads/tus-php/vendor/guzzlehttp/guzzle/src/Middleware.php(69): GuzzleHttp\\Exception\\RequestException::create()\n#1 /home24/muniv/downloads/tus-php/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}()\n#2 /home24/muniv/downloads/tus-php/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\\Promise\\Promise::callHandler()\n#3 /home24/muniv/downloads/tus-php/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\\Promise\\Promise::GuzzleHttp\\Promise\\{closure}()\n#4 /home24/muniv/downloads/tus-php/vendor/guzzlehttp/promises/src/Promise.php(2 in /home24/muniv/downloads/tus-php/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113, referer: http://dog.seedhost.eu/muniv/downloads/tus-php/src/basic/

**Comment by samundra** [comment]
Hi @muniv11111 From the log, you are getting `401 Unauthorized` that means `http://dog.seedhost.eu/muniv/downloads/tus-php/files` is not accessible. You will have to ensure it is publicly available.

This solely depends on your Apache Server Configuration.

**Comment by ankitpokhrel** [comment]
Closing due to inactivity. Feel free to comment to reopen if you still need help.
